### ISSUE TITLE
No boxes on electronic pdf file

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#117]
I just uploaded an electronic pdf file (PPN 333083768, "Strategieberatung im Zentrum der Macht") and I can't see any boxes after the OCR processing. Because of that I can't even see internal/external resources. What went wrong?

**Comment by kleinann** [comment]
The same happens with ppn 333083709, "Die klassische Moderne (2011)". It doesn't seem to be processed at all.

**Comment by kleinann** [comment]
I retried "Die klassische Moderne" with the same result: no bounding boxes at all. It's in the todo list under OCR processed.

**Comment by lgalke** [comment]
Good to know. @rtahseen the retrieved list of entries is also completely empty.

**Comment by anlausch** [comment]
I will also investigate on this. I can see in the logs that the OCR component returned lots of errors in the last hour, but maybe the status should not have changed.

**Comment by anlausch** [comment]
The status is now set back properly, such that the scan should appear again in the todo list, when ocr processing fails.

**Comment by rtahseen** [comment]
Can someone provide me the files "Die klassische Moderne" and "Strategieberatung im Zentrum der Macht"? So that I can look into the problem with these files.

**Comment by zuphilip** [comment]
@rtahseen Here are the two files: [333083768.pdf](https://github.com/locdb/locdb-frend/files/1434438/333083768.pdf), [333083709.pdf](https://github.com/locdb/locdb-frend/files/1434443/333083709.pdf)

**Comment by rtahseen** [comment]
I just looked into the above mentioned files and found out that there encoding issues during generation of these digital born pdfs. In simple words, they might look textual pdfs, but they are not.

**A Sample from given file:**
![screenshot1](https://user-images.githubusercontent.com/14193937/32280803-5334a4b8-bf1d-11e7-888e-4eccf0c5cd33.png)

We can see that it looks like textual pdf but if we try to select text then only partial text is selected. And if we try to copy paste the selected content , then we get something like this:

![screenshot2](https://user-images.githubusercontent.com/14193937/32280955-b04ebf44-bf1d-11e7-9056-3d78fd16aef7.png)

This means that there were some problems when this pdf was created. 
Additionally, I have also checked all the files in "e-pdf.zip" on owncloud. I found out that all the following files in Springer directory have same encoding issues:

![files](https://user-images.githubusercontent.com/14193937/32281185-62b1a93a-bf1e-11e7-8b7d-7b60269d041b.png)

**Solution:** Since these files are not truly textual pdfs, so I would suggest to process such files as image pdfs.

**Comment by kleinann** [comment]
Thanks, Tahseen. I uploaded an example of a true electronic pdf now (Rethinking business schools 
[44461205X.pdf](https://github.com/locdb/locdb-frend/files/1434892/44461205X.pdf)), and it works in principle. There are still some bounding boxes that are misplaced, f.ex. bounding box detection consistently fails at the beginning of the page because the header is taken for part of the first entry.

**Comment by anlausch** [comment]
I probably cannot detect such encoding issues automatically in the backend in an efficient way. Therefore, as a long-term solution, I would suggest to let the user input the type of pdf, and that we trust the user in these cases. @lgalke

**Comment by lgalke** [comment]
Out of scope for the workshop. Adding an input field is not that big of a deal. Still, when we have a textual pdf it would be desired to run ParsCit on the plain-text without converting to image (do you agree @rtahseen ?). For the workshop, we decided to process textual pdf as images. As soon as (after the workshop) textual pdfs get processed as text, I will add the corresponding input field.

**Comment by rtahseen** [comment]
@lgalke I agree. This was such an unforeseen case for all of us. In principle, both textual and image pdfs can be processed as image pdfs. For the time being we can adopt this solution to process all of our pdfs.

**Comment by anlausch** [comment]
@rtahseen  informed me that there are no coordinates calculated when processing textual pdfs as text. Therefore, @lgalke cannot show any bounding boxes when we use this configuration.
When we process textual pdfs as images though, coordinates are calculated and the front end can show bounding boxes. On the other hand, the extraction accuracy will decrease when converting the textual pdf to an image first while the extraction accuracy of the textual pdfs processed as text is really good.
Therefore, we have to decide on a trade-off here @kleinann @LauraErhard @zuphilip:
Option 1: We process the textual pdfs as images and can show bounding boxes, but the text extracted will probably contain errors as the accuracy decreases.
Option 2: We process the textual pdfs as text and cannot show bounding boxes but the extraction will be better.
What do you prefer?

**Comment by kleinann** [comment]
Sorry, I can't see where I can decide this. Could you give me a hint?

**Comment by LauraErhard** [comment]
![screenshot-2017-11-3 loc-db frontend](https://user-images.githubusercontent.com/32642653/32372161-000ecb10-c094-11e7-8df4-84871dfcde83.png)

**Comment by kleinann** [comment]
Thanks :-)

**Comment by kleinann** [comment]
I tried two textual pdfs (marked as such), "Behavioral Social sciences" and "Strukturvergleichsmodelle in den Sozialwissenschaften". When the pdf is processed, the entry stays under "OCR unprocessed" and lookes like the references came from Crossref. At least for "Strukturvergleichsmodelle", that cannot be true, because https://api.crossref.org/works/10.1524/9783486854008 has no references.
The entry list that results from the OCR processing is still incomplete, and it's difficult to process for a human because the scan isn't shown alongside.
--> I'd prefer to treat textual pdfs as images, at least for now.

**Comment by kleinann** [comment]
The OCR of the following file (textual pdf), when "is textual PDF" NOT checked, results in no entries at all.
[475963199.pdf](https://github.com/locdb/locdb-frend/files/1441247/475963199.pdf)
![grafik](https://user-images.githubusercontent.com/33151732/32377343-9b43a944-c0a7-11e7-964b-ee861f4dd0c6.png)

Could you look into that, @rtahseen?

**Comment by anlausch** [comment]
The OCR output of this is (pdfFlag='on'): 

<LOCDBViewResults>
<FilesFound>
<filename>20171103152635_475963199.pdf</filename>
</FilesFound>
<FilesNotFound/>
<algorithm fname="475963199.pdf" name="LOCDB Web service"/>
</LOCDBViewResults>

**Comment by rtahseen** [comment]
This seems to be a ParsCit issue. As ParsCit has some heuristics to detect a reference i.e. by parenthetical reference indicators "[1]", direct reference numbers "1" or unmarked strings. ParsCit identifies an unmarked string as a reference, when it starts with the list of authors' names. The above mentioned document contains unmarked reference strings but it does not starts with authors' names list and it also contains "=" sign which causes ambiguity for ParsCit to classify it as a non-reference string, because no author's name has an"=" sign in it. Thats why there was no reference detected in this case.

**Comment by lgalke** [comment]
Might be tackled by the new OCR engine already. There was a also some bug lately regarding the filtering for entries that do have a `coordinates` property, but this might have been introduced by latest changes for less-reloads.
