### ISSUE TITLE
Not possible to commit link after editing an external suggestion

### ISSUE THREAD

**Issue by kleinann** [locdb/locdb-frend#147]
I added a publication year to an external suggestion, clicked "Submit" and then "Commit link". Nothing happened, the reference stayed red in the list of references.

**Comment by lgalke** [comment]
Will check.

**Comment by lgalke** [comment]
Very good spot. The reason was that the resource-form creates a copy and naively updated the view to match the copy. Now the view is properly in-sync with the back-end at all states. For external resources the data updates are only stored locally in the front-end until submit is pressed. 

In any case, now the reference should turn green as desired. c540e5a

Please confirm

**Comment by lgalke** [comment]
For me, the issue seems to be fully resolved.
