### ISSUE TITLE
After deleting an entry I'm redirected to the project website

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#154]
After deleting an entry from the todo management, I am redirected to the project website (https://locdb.bib.uni-mannheim.de/blog/de/) instead of staying on the LOC-DB Extrapolite site. Is there a false URL somewhere?

**Comment by lgalke** [comment]
Will check in the train. Am 06.11.2017 09:39 schrieb LauraErhard <notifications@github.com>:After deleting an entry from the todo management, I am redirected to the project website (https://locdb.bib.uni-mannheim.de/blog/de/) instead of staying on the LOC-DB Extrapolite site. Is there a false URL somewhere?

**Comment by lgalke** [comment]
Fixed by 53df45c8447461258abe5b792b7d90ba55a15b78
Same problem was there with scans: 9a80c9850b935010f9b6add4dfdbfe6b95a44137

Hope it does not appear somewhere else.
