### ISSUE TITLE
Stucked entry in OCR unprocessed

### ISSUE THREAD

**Issue by kleinann** [locdb/locdb-frend#155]
We have two entries that stay in the OCR unprocessed tab unless they are already OCR processed:
"Using IBM SPSS statistics for research methods and social science statistics"
--> is also in OCR processed
"Rethinking business schools"
--> References are clickable, but entry appears only in OCR unprocessed

**Comment by lgalke** [comment]
There seems to be a problem with the status of the todo item in general. @anlausch do you have an idea of what causes this behaviour? It could also be possible that they still have some scan in the OCR Processing queue (the `IN_OCR_PROCESSING` scans might not be displayed in the `NOT_OCR_PROCESSED` tab).

However, I included some brute-force guard, so that the Resources are now shown iff they have `parts` (external Crossref References) or `scans` or any of their children satisfy this property.

Please note that I can for now do nothing about the ones that have `parts` (from CrossRef) since otherwise these ones would also be hidden inside the `External` tab.

(Deployment takes a little out of the train, but will be in some minutes also on production)

**Comment by lgalke** [comment]
It turns out that these stucked ToDo items do not have any `status` property at all. Instead they has `parts` containing a lot of entries which came at some point from crossref. @anlausch is this just an artefact from prior versions?

**Comment by lgalke** [comment]
We will continue discussion in #167 .
