### ISSUE TITLE
Use GBV-Zentralindex

### ISSUE THREAD

**Issue by anlausch** [locdb/locdb-frend#163]
In the future, we should use the GBV-Zentralindex instead of the SWB SRU interface

**Comment by zuphilip** [comment]
I don't think we should use it "instead" but maybe "additional". CC @kleinann

**Comment by anlausch** [comment]
I was told that it will contain basically the same contents but provides better performance?

**Comment by kleinann** [comment]
I guess what you mean is not the GBV-Zentralindex but the Gemeinsamer Fernleihindex. Thomas Kees, one of the participants of our workshop suggested this to me, too. The Fernleihindex contains the data of all the German library unions, the GBV-Zentralindex only those from the GBV - so the Fernleihindex really makes more sense and could be used instead the SWB SRU (and should be much faster). The problem is that we get records from every union catalogue for the same title, so we should probably think about filtering or preference ranking here, too. I'm not sure how to access the Fernleihindex; but the responsible person at the SWB is Volker Conradt. Should I contact him? 
The search interface for humans is here:
https://fernleihe.boss2.bsz-bw.de/

**Comment by anlausch** [comment]
I think this feature is added now as in the newest version we are also searching in GVI and K10Plus. Feel free to open this again if this is insufficient.
