### ISSUE TITLE
ToDo states considering external references

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#167]
The state of `ToDo` items does not allow to decide what to display.

Currently, the following cases can occur:

1. `parts` is given, then a references list-of-entries will be displayed and scans disabled (CrossRef suggestions are assumed)

2. `scans` is given, which result in one button for each scan, reflecting the entries on this scan.

3. both are given..

In the first place that distinction should suffice, however when there is a pdf uploaded to a former purely electronic journal, this might lead to inconsistencies. Plus, currently there are a lot of monographs that also have a `parts` property and thus receive a `References` button. I doubt that all of them were former electronic journals.

On the long-term, this temporary solution might be not well-suited. @anlausch would be happy to hear your thoughts on this. So far I struggle to come up with a good long-term solution.

We could stick to the existence of `parts` in a ToDo item to indicate necessary checking of externally ingested references. However that also causes certain difficulties when updating the meta data (I hope it is enough to not update the `parts` field). Still at some point the `parts` field also gets filled with the **real** entries and you would need to seperate these from the **externally** ingested ones in the back-end. Maybe for long-term we might prefer to carry these externally ingested references (from CrossRef) in a seperate property?

**Comment by anlausch** [comment]
I am also not sure how to properly reflect the workflow regarding this. I will think about this today.

**Comment by anlausch** [comment]
In order to redesign the todo-management, I wrote down the requirements and we have. Is this correct?

LOC-DB: To-Do Management

The behavior we want:
- Print resources
After OCR-processing, they should contain Bibliographic Entries as well as a processed Scan and be visible for checking and linking; In the future, the OCR-processing will be triggered automatically. Therefore, we do not need a todo-list for OCR-unprocessed scans. 
*Alternative: We want the todo-list because it might happen that the OCR-Processing fails. Then there need to be an option for manual triggering.*
- Electronic Resources
Here we have to distinguish three cases:
a) The references are available on Crossref
We could either add the br then to the same todo-list as above or to a different one. But, similar to the situation with print resources, the only steps that need to be performed are the checking and linking *(no scan will be uploaded for those, right?)*.
b) The references are not available on Crossref. Therefore, the librarian uploads a scan. Then, the behavior we want corresponds exactly to the Print Resource behavior.
c) The references are not available on Crossref, therefore, the librarian uploads the html source code of the references page on the publisher website

For all cases: Only if all BEs are linked, the BR shall disappear from the todo-list.

**Comment by lgalke** [comment]
Ref #178

**Comment by lgalke** [comment]
On `ToDo` level, the `parts` property holds all external references, which will be displayed in the References button.

**Comment by kleinann** [comment]
This might be a stupid question, but why are references "parts"? I thought there would be a different kind of relation between a part and a container (type "has part" - "is part of") and a citing resource and its references (type "cites" - "is cited by").

**Comment by anlausch** [comment]
It's not a stupid question. We also thought about this for some time, but it's just the way they designed it in the OC data model.

**Comment by lgalke** [comment]
`partOf` is unfortunately not the inverse of `parts`, yes. @anlausch does the new data model provide any enhancements in the ToDo management regarding this issue aswell?

I found already that `saveScan` and `saveElectronicJournal` are unified in `saveResource`, which is good.
Are there any changes apart from that? Let me know.

**Comment by lgalke** [comment]
We do not distinguish anymore between the two things. Any resource can have parts (read: external references) and/or attached scans.
