### ISSUE TITLE
Field in metadata 

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#169]
I just uploaded the file for the PPN 352226064 and I saw the curious category "TBA":
![screenshot-2017-11-10 loc-db frontend](https://user-images.githubusercontent.com/32642653/32652108-8060a97c-c603-11e7-8062-53f40b19c1b1.png)

Why does the system guess TBA? Does TBA stand for "to be announced"?

I checked the SWB and the number comes from the field [2201](http://swbtools.bsz-bw.de/cgi-bin/help.pl?cmd=kat&val=2201) and that is the field for the European Article Number (EAN).

**Comment by lgalke** [comment]
@anlausch , do you have an idea?

**Comment by anlausch** [comment]
I was not sure which identifier scheme to put, as it was not in Annettes mapping. The MARC21 field is 024 a, which contains according to the documentation [1] a standard number or code.
That's why I put tba for the beginning. I will check again whether it is always EAN or whether there have to be more checks in order to be sure.
[1] https://www.loc.gov/marc/bibliographic/bd024.html

**Comment by LauraErhard** [comment]
I just randomly checked a few number fields from the SWB and found a Universal Product Code (UPC) which is also exported in the MARC21 field 024a.
Therefore it is not always the EAN.

**Comment by anlausch** [comment]
Shall I just omit the field for now if I am not sure about the identifier scheme? Then it does not look weird on the frontend.

**Comment by anlausch** [comment]
I removed this part now. And deployed the version accordingly. This should not happen anymore. If someone wants to see EAN or something related, let me know.
