### ISSUE TITLE
[WIP] Transition to Bootstrap4

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#174]
We are transitioning the underlying version from bootstrap v3 to bootstrap v4. Some things might look a little odd in the meantime, but in the end everything will look better! If there is something style-related that is bothering you, please feel free to add to this issue.

**Comment by lgalke** [comment]
- [ ] bg-primary should not get inherited inside accordion group

**Comment by LauraErhard** [comment]
Is the transitioning still going on? I just noticed that the scan view sometimes has the file upload component right in the middle of a scan. Is this because of the bootstrap transition? 
![screenshot-2017-11-15 loc-db frontend](https://user-images.githubusercontent.com/32642653/32838116-333cab6c-ca10-11e7-8006-da392da311ba.png)

**Comment by lgalke** [comment]
Ohh this is interesting. Thanks for reporting. I will have a look whether I can reproduce the problem. Plus, I will update the dev version just now, so that we are in sync.

**Comment by lgalke** [comment]
Could you try it once more please? Could be related to some other bug which was just fixed.

**Comment by LauraErhard** [comment]
I checked several scan views and it never happened. I think it is fixed now. Thank you.
