### ISSUE TITLE
Show information about the resource in the reference/scan view

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#180]
Can we show some information about the ressource one is currently working on in the reference/scan view? For example something like the beginning of the title and an info button:

![info-ressource](https://user-images.githubusercontent.com/5199995/32881324-2d38bbce-cab1-11e7-8861-d33b9ec671bf.png)

(Note: This is only a first rough sketch.)

**Comment by lgalke** [comment]
Yes, we also thought about this. Will keep you updated here.

**Comment by lgalke** [comment]
https://getbootstrap.com/docs/4.0/components/breadcrumb/

@chah3d would you please take care of it by making use of the bootstrap4 component above?
Our component to extend would be the [todo-detail](../tree/master/src/app/todo-detail).

You might need to pass the resource to which the scan belongs through e.g. by adding the containing resource to the click handler `onSelect(scan, resource)` instead of `onSelect(scan)`. In the `app.component`, you can reuse the `source: BibliographicResource | ToDo` property.

**Comment by lgalke** [comment]
The new version containing a breadcumb is now online.
