### ISSUE TITLE
Short format for resources

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#186]
Striving for a unified **short** format for resources, we would like to adapt some commonly chosen reference format, such as ACM:

```
Sean M. McNee, Istvan Albert, Dan Cosley, Prateep Gopalkrishnan, Shyong K. Lam, Al Mamunur Rashid, Joseph A. Konstan, and John Riedl. 2002. On the recommending of citations for research papers. In Proceedings of the 2002 ACM conference on Computer supported cooperative work (CSCW '02). ACM, New York, NY, USA, 116-125. DOI=http://dx.doi.org/10.1145/587078.587096 

```

We are also open for suggestions regarding the exact format.
For now it would be: `<authors>. <year>. <title>. in <container-title>. <DOI>`

**Comment by zuphilip** [comment]
The ACM format looks for me okay and it is somehow standardized. There is ISBD but this comes from (printed) card catalogues. Some library journals use CMoS, but personally I prefer to have the date information at the beginning. Thus, you can IMO continue with ACM style (maybe we can reconsider that if this new feature is in place).

**Comment by chah3d** [comment]
Shortform Entries:
![selection_058](https://user-images.githubusercontent.com/32481062/37033173-4c506526-2145-11e8-9c5b-823c79452d98.png)

Shortform Ressources:
![selection_059](https://user-images.githubusercontent.com/32481062/37033165-4318649a-2145-11e8-9767-849cac2bb11e.png)
(`<authors>. <year>. <title>. in <container-title>. <DOI>`)

**Comment by lgalke** [comment]
This looks already promising. We just need to take this one step further to align it with the new data model. @chah3d can we meet tomorrow regarding this?

**Comment by zuphilip** [comment]
(Nit: The `in` after a point should start with a capital letter, i.e. `In`.)

**Comment by lgalke** [comment]
Just to make sure: When there is a container resource ("In: ..."), the year should correspond to the publicationYear of the container. Is this correct, or does it also somewhat depend on the format (e.g. where the year is placed). Of course, most of the time, in theory, the two match, but our application is not theory and it is relevant for implementation. Would prefer to have a guideline here, rather than pick anything that is non-null. A clear preference of which publicationYear to pick would help already. 

Regarding where to place the year, @zuphilip can you point us to some standardized format which has the publicationYear at the beginning and fits our needs also in other aspects?

**Comment by lgalke** [comment]
Starting from the 5 formats google scholar offers, there are two with year in front:

APA
```
Blom, H. A., & Bar-Shalom, Y. (1988). The interacting multiple model algorithm for systems with Markovian switching coefficients. IEEE transactions on Automatic Control, 33(8), 780-783.
```

or Harvard
```
Blom, H.A. and Bar-Shalom, Y., 1988. The interacting multiple model algorithm for systems with Markovian switching coefficients. IEEE transactions on Automatic Control, 33(8), pp.780-783.
```

The only differ in whether the year is braced or not, however they both seem to omit the "In:" which is quite common at least in Germany. Would like to stick to some well-known style which fits.

**Comment by zuphilip** [comment]
> When there is a container resource ("In: ..."), the year should correspond to the publicationYear of the container. Is this correct, or does it also somewhat depend on the format (e.g. where the year is placed).

There is no different semantic when the year is placed before the title or after. Actually, there is not one [Harvard style](https://www.zotero.org/support/kb/harvard_style), but this is rather a synonym for any author-date style, i.e. a citation style starting with author and date information. Traditional journals are published as complete issues and therefore the publication date of the article is equal to the publication date of the issue it is in. Nowadays, there are also journals without issues where the articles are published on a continuous base. Anyway, in our process the date is coming either from the metadata in the catalog or from the OCR. --> There is no difference in where to place the date information. However, for our process, the year is IMO more important to see fast and compare with the suggestions and thus I would suggest to have this before the title.

> Would prefer to have a guideline here, rather than pick anything that is non-null. A clear preference of which publicationYear to pick would help already.

I am not sure I understand the circumstances that we have two dates here, but given that this case occurs: We should prefer the date of the article over the date of the container.

> Regarding where to place the year, @zuphilip can you point us to some standardized format which has the publicationYear at the beginning and fits our needs also in other aspects?

I really think we shouldn't care that much about a citation style here but rather take a simple enough rule to display the bibliographic information. It is fine to be inspired by some citation styles, but there is no need to follow them exactly.

<details>
<summary>More Details</summary>

The APA style guide is a book containing at least 300 pages. The [CSL implemention of the APA style](https://github.com/citation-style-language/styles/commits/master/apa.csl) was steadily improved and this takes time we should spend to other tasks.

However, it might be crucial to see the DOI as well, which GoogleScholar does not show and therefore their APA formated string is wrong. But you see that for journal articles the journal title is put into italics instead of using an 'in'. But for us it is for example not clear in this state whether we deal with a journal article or an article in a proceeding. Put always an ' in' or put the container title always in italics is for our purposes fine.
</details>

**Comment by lgalke** [comment]
Thanks for all these details. This helps.
