### ISSUE TITLE
current reference not shown after `commit link`

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#198]
After I `commit link` a suggestion it isn't shown again on the right side if I click on the now green entry on the left. You see that the references category has an ID from a connected reference, but on the left side I don't see it. This issue doesn't occur every time but a lot of times.
Current Reference is shown:
![current reference](https://user-images.githubusercontent.com/32642653/33419293-0496bb04-d5aa-11e7-89c9-3fd015d4604e.png)
Current Reference is **not** shown:
![no current reference](https://user-images.githubusercontent.com/32642653/33419303-120a728a-d5aa-11e7-94d3-3ad17a33ef86.png)

You see that in the one where the current reference is **not** shown there is an `Invalid entry.references pointer 5a1eaf4668c73a6f0d451f84`
What is going on?

**Comment by lgalke** [comment]
Interesting discovery, the error message `Invalid entry.references pointer` is emitted **iff** the bibliographic resource corresponding to the references pointer could not be retrieved (does not exist). Will need to double check where the problem is exactly.

Just as a self-reminder. We need to make sure that:

1. the reference entry is not overwritten but its properties are reassigned similar to #197
2. Still, ngOnChanges gets called after the new resource has been created AND the reference has been updated.

**Comment by LauraErhard** [comment]
I can't exactly pin it down when it happens. If I am just switching between references in a reference list I see the 'currently reference' sometimes and sometimes it is not there. I can't discern a pattern.

**Comment by lgalke** [comment]
The desired behaviour should be that `currently references` is present if the reference already has a target, else not. When I just tried it, it seems to work. 

I tried it in `Quality & Quantity / The strong referendum paradox` as shown in the screenshot, but for me there was no reference linked so the `currently references` should not be present at all.

**Comment by LauraErhard** [comment]
It works for me now too. Maybe it was a temporary issue.
