### ISSUE TITLE
Volume, issue number, pages

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#199]
We need to have the information about volume, issue and pages in the external suggestions to choose the correct one.

**Comment by lgalke** [comment]
You mean in the shortened view?

**Comment by zuphilip** [comment]
The information in the suggestions seems to missing in general (at least sometimes):

![journal-article-suggestion](https://user-images.githubusercontent.com/5199995/33435824-7e8609f4-d5e3-11e7-951f-e720aa636afe.png)

The publication year would then also be great to have in the shortened view, to quickly select the correct edition etc.

**Comment by anlausch** [comment]
It is not possible to capture this with the current data model except that I create separate resources for this which then need to be mapped in the frontend. This will be solved with the new version where we intend to have the properties as discussed either in the child resource itself or one level up in the container resource.

For now, in order to just make it work somehow, I can just add the properties directly to the data model and fill them accordingly (similar to containerTitle). This will be a quite dirty intermediate solution but everything related to this has to be reimplemented again anyways. I will provide this asap.

**Comment by lgalke** [comment]
Would it be a problem to re-use the `number` property here?

Then we would have `containerTitle` and `number`, where `containerTitle` acts as a *soft* partOf relationship and we could define `number` to *number inside* containerTitle. Or is `number` already reserved for something else?

**Comment by zuphilip** [comment]
> Would it be a problem to re-use the `number` property here?

In OpenCitation's data model there is:
* `number` on the volume level, which means then the volume number
* `number` on the issue level, which means then the issue number

The number property in our curerent (not fully) hierarchical model can only capture one of these meanings, but not both.

**Comment by anlausch** [comment]
I also think that reusing the number property might be unsuitable here. Also, later on it could be difficult to determine what the semantics are.

**Comment by anlausch** [comment]
This issue should be solved with the new data model. I close this issue therefore now. Feel free to open again.
