### ISSUE TITLE
More types for newly created items

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#202]
For starting we need the types:
* monograph
* edited book
* journal article
* book chapter
* report (which we can also use for anything else at the moment)

**Comment by lgalke** [comment]
What is the expected behaviour of each. Until now we had JOURNAL  basically referring to a Journal *Article* in an electronic journal. I think @anlausch implemented already a unified interface for both electronic and textual input (/saveResource), is that right? If yes, we can decouple the resource type from its implied behaviour.

**Comment by anlausch** [comment]
In general, we should stick to the mapping provided by Annette for the resource types. I think currently every resource type that @zuphilip mentioned should be supported by the backend except for report (I thought that we discussed that you want to start with journal articles? And there I also do not know what should happen).
/saveResource was implemented in another branch but is now useless, because it was based on other assumptions regarding the data model and other requirements discussed with the librarians. I will reimplement this service again as soon as we have fixed all the changes that were discussed last time. Before that, unfortunately it makes no sense at all.

**Comment by zuphilip** [comment]
Sorry, I think that was unclear. I was talking about the linking (resolving) step. In the references of a journal article all kind of different types of sources can be mentioned, i.e. the drop down menu there should contain more values and whatever is needed for that in the background.

![types-new-resources](https://user-images.githubusercontent.com/5199995/33448148-8c178472-d605-11e7-87da-3baa4a0559c5.png)

**Comment by lgalke** [comment]
See also #175

**Comment by lgalke** [comment]
Now all OCC types are available in the dropdown.
