### ISSUE TITLE
Not possible to directly to /frontpage, /ingest etc.

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#203]
Directly input these urls will lead always to a 404.

**Comment by lgalke** [comment]
That is true because the app itself is never loaded. Can quickly check if it can be resolved in the front/end by a default route, but if the application is not loaded in the first place, this will not have an effect. Would in this case require some routing mechanisms on the http server itself, i.e. would need to ask Stefan Weil.

**Comment by lgalke** [comment]
> Can quickly check if it can be resolved in the front/end by a default route
No, it cannot be resolved in the front/end.

**Comment by lgalke** [comment]
Thanks to Stefan
