### ISSUE TITLE
Don't enlarge the bibliographic entries everywhere

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#209]
The new short list of bibliographic entries looks nice now and in most cases it is enough to just go over the shortened version. Can we enlarge this only by clicking to a small button and not everywhere in this area? Something like a green button here:

![short-list](https://user-images.githubusercontent.com/5199995/33437008-f62c6040-d5e6-11e7-9c73-2a93537e297e.png)

In this way one can go through the list without opening every entry. Moreover, the amount of scrolling could be decreased.

**Comment by lgalke** [comment]
We are planning to have one unified format for the short display of both, resources and references, and then just as you proposed, not auto-expanding anything on click but only if absolutely necessary (i.e. editing). See also: #186 . Would be nice to have a librarian-asserted short format here. For now I used ACM style for inspiration.

**Comment by lgalke** [comment]
Its not an issue anymore in the current dev branch.

**Comment by zuphilip** [comment]
Opening a new page for the editing is IMO worse then having the information together. What is the use case for the new edit page? When will I open the entry `5ae1be030a5ca46a3e4cb15b` and edit it?

**Comment by lgalke** [comment]
I agree that it is probably too much overhead when it comes to editing single reference entries (which I guess is very rarely done anyways). The change was performed when we tried to seperate the meta-data editing process from the linking process to have less of an *all-in-one* overload GUI, but more modular.

We have 3 editing use-cases:

1. Edit Resource Meta-data (left-hand-side of linking)
2. Edit Entry Meta-data (rarely used) 
3. Edit Suggestion Meta-data (right-hand side of linking)
4. Create new Resource from metadata (in this special case editing is mandatory to decide for a publication type)

And various options for how to display the edit form:
- Modal (like a pop up)
- In-Place (Drop down)
- Dedicated page for editing

Right now we opted for a link to a dedicated view for use cases 1. and 2. because it leads to less cluttered agenda view and the linking process.

For use case 3 we retained the In-Place option. We already noted the preference of In-Place over Modal in case of suggestions to enable this kind of 'split-view' where the reference entry metadata can be used for adjustment.

For number 4, we need to know the publication type and therefore we imposed a modal right now. (afterwards it is also in-place just as the other suggestion types)

We can revert to any of the other options, it would be great to hear your preferences. What's your take @zuphilip and also the others @LauraErhard on editing resources in general?

**Comment by LauraErhard** [comment]
I think we don't use the first use-case at all. The only time we have to change something from the reference list is if we want to add an entry or if we want to delete one. Maybe we should replace the "Edit" button with a delete button (of cause there should then be a message with "are you sure that you want to delete this" to avoid clicking on it by accident). We should discuss this more.
 
I have no strong opinion on the second use-case, because if the metadata import from crossref/SWB... works perfectly we wouldn't require an edit button at all.

I'm for the in-place display option for use-case 3 & 4 because as you said it enables us to use the reference metadata for adjustments.

**Comment by lgalke** [comment]
In our design session today we summarized that the functionality is rarely needed, there is room for improvement, but may become complicated. Editing should be side-by-side with scan, or with other browser window. Because it is rarely used, we decided that it is not a top priority at the moment.

**Comment by lgalke** [comment]
We reverted to inline forms but do not auto-open everywhere. Hope it's now fine this way.
