### ISSUE TITLE
400-error "Bad request"

### ISSUE THREAD

**Issue by SylviaZander** [locdb/locdb-frend#224]
I just got these error message when saving:
![400 error](https://user-images.githubusercontent.com/32641017/34763815-c23afdfc-f5ec-11e7-8940-fee2fd00d0d1.PNG)

I wanted to commit link a reference (Bauman, Z: Conversations with Zygmunt Bauman) with an external ressource (SWB) when the error occured

**Comment by lgalke** [comment]
This is a problem is caused by the empty AUTHOR field. Please try to edit the resource and remove the *empty* `AUTHOR` field from the contributors. When an author is given, also a non-empty nameString value is expected by the back-end. As of now, these empty fields do *not* get removed automatically. 

We will keep this in mind as an enhancement for the next major update.

**Comment by SylviaZander** [comment]
Yes, I removed the empty AUTHOR-field and it works now. Thanks !
