### ISSUE TITLE
Agenda view: container resources

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#317]
As far as I could see, the right information is now in the container resources. Thanks for your work on that.
I just have some ideas/notes/questions for the short format:
1. Why do the container resources don't have a type & year anymore? Was there a specific reason we excluded them? For a better overview I think they would be helpful.

2. We would like the container title to be bold (in the child, we don't want the container title bold)

3. Apparently if a resource only has the main title a / is displayed at the end. This looks kind of strange with the , following right behind (see example below). Is there a way to cut that part from the title?
![2018-06-12 short format_container](https://user-images.githubusercontent.com/32642653/41295787-adc4d1d0-6e5b-11e8-880b-06ba094b8420.png)

4. With journal issues I would like to change the order of the information. Right now I think we have `journal title` `issue title` `volume` `publisher ` `issue`. I would prefer `journal title` `issue title` `volume` `issue` `publisher`. On top of that it would be nice to identify volume and issue as such. Most of the time you could guess which is which, but it would be easier if the information shows this directly (e.g. `volume 37`, `issue 5` or a short version like `volume(issue)`).

**Comment by lgalke** [comment]
Hey @LauraErhard, thanks for your feedback. A few remarks:

1. For the year, we once decided that it is usually the same for the container and the child. We picked the one of the child, as it is more appropriate in the very rare case it is not the same. The types of the containers could be added, I agree.

2. Please clarify:

> We would like the container title to be bold (in the child, we don't want the container title bold)

3. That's a data issue: edit the resource and remove the trailing `/`.

4. We can prepend the 'volume' and 'issue' labels, of course. The ordering can, of course, also be changed, but we might a little more time for that (due to how we generate it right now).

**Comment by LauraErhard** [comment]
1. okay it makes sense, thanks
2. The container resource is completely not bold, therefore it kind of gets lost. I think if the green part is bold that would help. I didn't know if this change would influence the `in` part in the child therefore I specified, that this part (red in the examples below) should stay as it is.
![2018-06-12 short format bold](https://user-images.githubusercontent.com/32642653/41298813-5c42cfea-6e62-11e8-9a52-77fe0233e57d.png)
![2018-06-12 short format bold2](https://user-images.githubusercontent.com/32642653/41299021-cf213786-6e62-11e8-8ced-90af577fe34a.png)
I hope this helps.
3. I was hoping you could do it automatically. But okay.
4. The labels would be really appreciated. And for the long term I think we should change the order.

**Comment by lgalke** [comment]
Regarding point 2: Ah, thanks I see now what you mean. We will fix it.
Point 3, I would forward to @anlausch since it is metadata-gathering related, but I'd say it's not too urgent.

**Comment by anlausch** [comment]
The trailing "/" is often coming from the metadata from the external sources, e.g. SWB. I could remove it, but I thought that I better leave the metadata as it was cataloged. What do you think?

**Comment by SylviaZander** [comment]
The trailing "/" is used in the bibliographic title recording as a descriptive symbol to separate the title from the contributors. In the LOC database, we use a comma as separator for the individual details. Therefore, the "/" is not necessary (but rather redundant because it is a double seperator) and it would be convenient for us if it is not shown.

**Comment by lgalke** [comment]
I added the type of the container, and also the year because I observed that oftentimes there is no year metadata for the child. For now both are activated. We still need to adjust the ordering and add the labels to the issue and volume number.

**Comment by lgalke** [comment]
This should be fixed by now. Please verify.
