### ISSUE TITLE
Not possible to edit container metadata

### ISSUE THREAD

**Issue by kleinann** [locdb/locdb-frend#326]
It's not possible to edit or add metadata that belongs to the container, neither if the come from an external source nor if they are created as a "new resource from reference metadata".

Example:
In http://journals.sagepub.com/doi/10.1177/0001699311412798
Crossref delivers a reference list with the following entry:
Mortensen DT. 1970. In: American Economic Review 60 

When I try to create a "new resource from reference metadata", I get the following:
![grafik](https://user-images.githubusercontent.com/33151732/41546158-38082d5e-731d-11e8-81b4-f2c046cfc072.png)
There is no possibility to correct the journal title or even see if it's there.

**Comment by lgalke** [comment]
This feature is indeed necessary at some point. We need to think about how to make it work properly while being consistent with our two-level hierarchy. The state is that child holds only its own metadata and parent holds the rest.

In the case you described above we would create an 'orphan' with insufficient meta-data, but it would not fit our two-level policy to put all the meta-data in the child. We need a way to properly links the 'new child' to an existing parent (also here #314 could help). Only if the parent does not exist yet, we could think of a convenient way to initiate creating a new parent.

Apart from that, we are also aware that when editing a (flattened) containers, there are still some properties missing due to the flattening. For instance, inside issue and volume containers the journal title etc. should be editable at some point.

**Comment by lgalke** [comment]
For editing (possibly flattened) containers, we need to dynamically adjust the shown fields in the form.
From issue #271, we can also tackle that the date input should be only the year in case of books and monographs but the full date for other resource types.

**Comment by LauraErhard** [comment]
> Only if the parent does not exist yet, we could think of a convenient way to initiate creating a new parent.

We have to keep this in mind for the journal articles pdf, which we ingest via DOI. Because there is no metadata available and we have to manually change the `partof` for each article/issue. Usually the right parent is not yet available.

**Comment by lgalke** [comment]
@chah3d this should be the next thing to tackle :+1:

**Comment by lgalke** [comment]
The issue is three-fold:

- [ ] Depending on the resource type, make additional fields visible and editable (for instance: JOURNAL_TITLE should be there for all JOURNAL ISSUES and JOURNAL VOLUMES, and so on)

- [ ] Allow convenient switching from the editing of a contained resource to editing its container metadata Maybe: in the inline form, make a switch (as we have for Scan View / List View in the ScanInspector) to toggle to the Container resource.

- [ ] Think about how to allow workflows like "Creating a new child": Essentially,switch the role of the current meta-data to be the container, and start a new resource to be the child.

**Comment by lgalke** [comment]
I started working on it:

![screenshot_20180905_140647](https://user-images.githubusercontent.com/3439126/45092228-120be880-b115-11e8-815e-ed3ccf1dba9c.png)

But the direction where this goes seems to be quite uncomfortable. The standard properties (which we also use for display) are now displayed, depending on the resource type, and editable. However, there is a lot missing (identifiers, contributors such as publisher, ...). Guess there should be a more generic approach.

Some idea would be to dynamically switch between shown properties, like so:

1. Resource Type: 'Journal_Issue' (drop-down, as we have it now)
2. View properties for: 'Journal' (other drop-down, decoupled from actual type, just to dynamically change the properties).

3. all type-dependent properties (title, subtitle, number, edition, volume, contributors, identifiers, year), but with respect to the type of 2.


 @kleinann @LauraErhard what's your opinion on this?

**Comment by LauraErhard** [comment]
Just some of my thoughts on this:
a. To show and be able to edit every property of the parents you need to display the different parents separately (therefore the drop-down menu and not a combined view like you implied in the screenshot)?
If the seperate view is necessary, would we really need a drop-down menu? You mentioned in the comment above:
> Maybe: in the inline form, make a switch (as we have for Scan View / List View in the ScanInspector) to toggle to the Container resource.

Would that still be a possibilty? I think it would be faster if we just had buttons like the Scan View / List View.

b. If you put the `container properties` at the end of the child it would potentially blow up the entry. Maybe we could think about having buttons like this
![buttons](https://user-images.githubusercontent.com/32642653/45218286-63e47800-b2a7-11e8-974b-d5c93c40db0b.png)
somewhere at the top, to switch back and forth between the parents and children?!

c. Would the `part of` field stay in the child? Or would I do the autocompletion in the `container properties`?

d. Would the `container properties` only automatically appear if I choose a resource type with possible parents? And if I change for example resource type from chapter to monograph the `container properties` would instantly disappear?

@kleinann @SylviaZander @zuphilip what do you think?

**Comment by lgalke** [comment]
Hey @LauraErhard, thanks for your thoughts. They are really helpful.
Making everything work smoothly is quite complicated. I started a first few tries, but always there were some hassles which make it not very smooth.

Unfortunately I doubt that I will come up with an implemented solution today. The most promising approach so far is some kind of meta-control panel, which takes care of the following (global) things:
- Determine whether to show the child or the container (article, or issue)
- Allow edits of the partOf property (or create a new Container for it)
- Allow edits of the resource type
- Determine which attributes to show+edit (issue, volume, journal)
and below show the form for the attributes as we have it now

However, it is still quite complex since even these meta-properties can interact in various ways:


- Changing the type implies copying the property one place to another (other data might be overwritten)
- Changing the type affects the possible parent containers and could dramatically invalidate the other data (flattened data is basically lost when you change the type to something else)
- The `partOf` property would actually invalidate / or change the current container resource

While I guess that the most-recent idea with some controller that takes care of these special cases is promising, I doubt that I'll be able to solve (and implement) all those issues today and unfortunately I'll be in vacation for the next two weeks...

What would help is what type of use-cases are most-common and important, and which ones can maybe be even disregarded.

**Comment by lgalke** [comment]
> c. Would the part of field stay in the child? Or would I do the autocompletion in the container properties?
The idea of the data-model is that there are only two hierarchy levels: containers and childs... So the part-of field would stay in the child.

> d. Would the container properties only automatically appear if I choose a resource type with possible parents? And if I change for example resource type from chapter to monograph the container properties would instantly disappear?

Yea that's actually a major part of the problem, changing types and still having the data at the correct places... but that would be the idea, yea (see challenges from comment above)

**Comment by kleinann** [comment]
I think we should really start from the use cases.  

I imagine the following as being most frequent:

- We want to link a book chapter, but can only find the containing book in the suggestions. We'd then want to take the book and create a book chapter (--> a child resource) from it. 

- We find a journal article which is part of a journal issue that does not yet exist in our database. We'd want to create the new issue, and if a different issue of the same journal does already exist, we want to use this as a template (all the journal related fields will be correct, and we'll usually just have to adapt the volume and/or issue number). 

Later maybe also: 

- We want to link a journal article for which we already have the journal issue in our database, but we can't find suggestions for the article. We'd then want to use the existing journal issue and add a new child. 

Is it really necessary to **change** the resource type? For the above mentioned cases, the function needed would rather be "add child" and "add/edit parent" - this changes the relation of the resource to others but not necessarily the type (a book stays a book even if it's now the container of a chapter). 

In general, I can of course think of cases when changing the resource type would make sense (e.g. if it's just wrong), but is it crucial for the issue that we're talking about here?

**Comment by kleinann** [comment]
> The standard properties (which we also use for display) are now displayed, depending on the resource type, and editable. However, there is a lot missing (identifiers, contributors such as publisher, ...), in the worst case, these properties could also extend over 2 hierarchy levels.

I don't really understand the problem here. Why are these properties missing? 

Judging from the screenshot, I guess that it would be a bit confusing to just show all container properties at once. Actually, for journal isues there are a lot of them that will be very seldom used. I'd suggest to show only the most important ones for each hierarchy level and add a possibility to see all of them if necessary ("More").

In my mind, the most important properties for a journal issue would be:
journal_title
journal_subtitle
journal_identifiers
journal_contributors
journalVolume_number
journalIssue_number

**Comment by lgalke** [comment]
Thanks @kleinann , that is very helpful. In our data-model basically everything is possible, so such constraints can alleviate us from being super-generic and help us to *not* pass all the confusion over to the users.

**Comment by lgalke** [comment]
I've added the suggested properties to our mapping to 'foreign' properties:
```
  export function foreignPropertiesByType(containerType: enums.resourceType): Array< string > {
    /*
     * This is a mapping to obtain relevant (but not own) properties for a flattened container type
     * It is intended to offer the foreign but relevant fields in a form.
     *
     */
  
    const rtype = enums.resourceType;
    switch (containerType) {
      case rtype.journalIssue:
        // when its an issue, we need properties of volume and journal
        return [typedProperty(rtype.journal, 'title'),
                typedProperty(rtype.journal, 'subtitle'),
+               typedProperty(rtype.journal, 'identifiers'),
+               typedProperty(rtype.journal, 'contributors'),
                typedProperty(rtype.journalVolume, 'number')];
  
      case rtype.journalVolume:
        // if its a volume, we need properties of journal
!       return [
!         typedProperty(rtype.journal, 'title'),
+         typedProperty(rtype.journal, 'subtitle'),
+         typedProperty(rtype.journal, 'identifiers'),
+         typedProperty(rtype.journal, 'contributors'),
+       ];
  
      case rtype.monograph || rtype.editedBook || rtype.book || rtype.referenceBook:
        // in these cases, the book series and sets are flattened.
        return [typedProperty(rtype.bookSeries, 'title'),
                typedProperty(rtype.bookSeries, 'number'),
                typedProperty(rtype.bookSet, 'title')];
      default:
        return [];
    }
  }
```
Note that journalIssue_number is not included here, because it will be the 'own' property of the issue and not a 'foreign' (read: flattened) one.

It still requires some effort, especially since identifiers and contributors need special treatments, but I guess its a good starting point. Let me know, when there is more to add to the list of "relevant foreign properties per type" (above you see the full map we have at the moment).

**Comment by lgalke** [comment]
We just deployed a first version with explicit support for editing container metadata on dev. Please feel free to test it.

**Comment by lgalke** [comment]
We have now a dedicated component for managing the resource and container properties. Plus, we conditionally display the additional fields in the form. #376
