### ISSUE TITLE
No scroll options for scanned images

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#328]
In the resolve step there is currently no scroll option for scanned images. But this means that e.g. the very last reference is at the bottom of the page and all the suggestions are at the top of the page. Therefore, comparing the visual reference with the suggestions is not possible at the same time and the users need to switch from top to bottom and back again all the time during working. Can this be changed?

It looks that the scroll option is already there but the image size is not restricted. Can we restrict the image size similar to what is don for the references?

**Comment by lgalke** [comment]
Thanks for highlighting this! We will have a look until at it until tomorrow.

**Comment by lgalke** [comment]
Just to update you, we figured out why we disabled scrolling at that point. It was a minor issue with the interaction with the svg, since the scan did exceed its view container and rescaling doesnt work with the bounding boxes etc. I propose maybe to wait until the new OCR engine is connected, because this one would split large scans into single pages anyway. So maybe we are fine then. In the worst case, you can still zoom and change the location a little, but we are aware that it is not very convenient. So if needed, we will find a way to fix this problem, but only after the new OCR engine is connected.

**Comment by zuphilip** [comment]
> It was a minor issue with the interaction with the svg, since the scan did exceed its view container and rescaling doesnt work with the bounding boxes etc.

I am not sure that still holds. Because when simply changing in my browser the CSS to:
```
   .card-body>div:first-child {
        max-height: 1000px;
    }
```
then scrolling is enabled and also zoom out, move the picture and zoom out seems to work without any problems.

**Comment by lgalke** [comment]
It's implemented and deployed. Thanks!

**Comment by zuphilip** [comment]
Okay, it works. But I see two scroll bars now, one which is activated and another one is deactivated. There are two nodes with the `scroll` option and maybe reducing this to one would improve the display.
