### ISSUE TITLE
Adjustable Bounding Boxes

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#347]
- [x] Check if ~~d3~~ interact.js conveniently supports adjustments
- [x] Connect svg bounding boxes with interact.js
- [x] Add possibility to adjust bounding boxes
- [x] Properly store the new data
- [ ] Notify back-end about the update
- [ ] Trigger OCR Processing on the single slice! (backend API required)

**Comment by anlausch** [comment]
@lgalke We can check together but I think that triggering OCR processing on a single page is already possible. But, I am wondering whether this is enough -- do we maybe need another OCR service which saves the new annotations and maybe retriggers training?

**Comment by lgalke** [comment]
Update: OCR endpoint is present and interfaces are specified. We are starting with the implementation in the front-end, but we also need a dedicated back-end service to actually make it work.

**Comment by lgalke** [comment]
The functionality is implemented on the dev deployment point @LauraErhard @kleinann @zuphilip @SylviaZander . However, the updates do still fail @anlausch @rtahseen please verify the coordinate update operation.

**Comment by rtahseen** [comment]
I just double checked. It works for alright me. Are you using correct filename?
Can you share the parameters you are using to send request to Automatic Reference Extractor?

**Comment by lgalke** [comment]
@anlausch said that it could be the case that it does not work for older scans as the filenames are somehow obsolete. Is that possible @rtahseen ?

**Comment by rtahseen** [comment]
yes it might be the case, because it was a fresh deployment and did not contained any results processed with older version.

**Comment by lgalke** [comment]
Ah okay, then maybe we are fine ;)

**Comment by lgalke** [comment]
Further extensions in #390 before we can merge #388

**Comment by LauraErhard** [comment]
I just checked this out in the dev system and I noticed, that in Chrome it works fine, but Firefox seems to not handle the moving of the boxes right. If I want to move a box the box either appears in the left upper corner or disappears completely. We primarily use Firefox so it would be nice if it would work there as well.
I couldn't test the `save bounding boxes` because we were not yet able to get new uploads into `ready`. With the "old" uploads I got an error. But I think that was expected.
