### ISSUE TITLE
"ready" & "Electronic Journals" part doesn't show entries

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#353]
![readydoesn tload](https://user-images.githubusercontent.com/32642653/44720289-9b446f00-aac6-11e8-9f1e-ca051f0d65c4.png)

I see entries in "waiting" & "in queue", but the "ready" & "Electronic Journals" part doesn't show entries. What is the issue?!
I think the second error is from me testing the autocompletion, but that shouldn't influence the view?!

**Comment by lgalke** [comment]
For me, the ready and electronic journals are shown again. Does it work for you?

The error msg tells that there is some data inconsistency, where the `_id` field is holding the plain title string instead of a proper id. This might be caused by recent development progress for #326, I'll have a closer look.

Anyways, the retrieval of agenda items should be stable even if there is one buggy resource in the database.

**Comment by LauraErhard** [comment]
Now I see everything again too. Did you do anything?

**Comment by lgalke** [comment]
No, maybe @anlausch can give more information?

**Comment by anlausch** [comment]
The issue was really this: "The error msg tells that there is some data inconsistency, where the _id field is holding the plain title string instead of a proper id. This might be caused by recent development progress for #326, I'll have a closer look." I really need to put more restrictions on the field to prevent this from happening. I'll keep the issue opened until this is done.

**Comment by anlausch** [comment]
I added explicit string pattern validation to all fields holding an _id. This should be sufficient in order to prevent problems similar to this. Let me know if this causes problems. https://github.com/locdb/loc-db/commit/0e6aaee3806d992ad5b09801cec56f3491e196bb
