### ISSUE TITLE
Small issues

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#364]
1. Ingest part:

a. Add electronic resource
- [x] preselection should be journal article (not journal), because this is the most ingested electronic resource
- [ ] resource type monograph & book should have the possibility to upload via DOI (not a priority, because we don’t have a use case for this, but future users could find this useful)

b. Add batch of files
- [x] most of the resource types only have one possible `identifier scheme`. It would be great if these were automatically selected. Only `proceedings_article` and `book_chapter` have two possibilities to choose from and I would preselect `SWB_PPN` for both of them. 

2. Resolve:
- [x] in the edit resource menu after clicking `confirm` there should either be a little message, that gives feedback, if the changes were successfully saved or you should be brought back to the resolve list (right now we get no feedback whatsoever and we are not even sure if anything happened)
- [x] the list of the different pages you get when clicking `scan` is quite confusing. It would be easier for us if only the right page number is shown and not the whole information (XX – YY). Would it be possible to just count upwards till the last page or something like that?
- [x] Would it be possible to sort the chapters for example on the basis of page numbers in the right order? Some context: I uploaded the first few chapters of an edited book together and the OCR/reference extraction took different amount of time so the chapter list was out of order. To have this in the right order we would have to wait till a chapter gets processed and then upload the next one. This is just a beauty upgrade and doesn’t affect our work (=not a priority)

**Comment by lgalke** [comment]
1. a) @anlausch, would this be fine for the backend? When I remember correctly, I introduced these constraints based on a list that you provided. Also the journal thingy used to be quite special since the identifier referred to the journal and not the newly ingested article, but I am actually not 100% sure how it is handled today. As I already mentioned in other issues, best would be to drop resource type as required field for ingestion (because if metadata is found, the resource type is overwritten anyways, if nothing is found, we can still select a reasonable default, like REPORT, and manually change later it.
 
@anlausch could you provide some details about the effect of the resource type and whether it makes sense to consider dropping this requirement?

b) Yes, we can do that, but I'd prefer to drop the resource type altogether (as explained in a).

2. Resolve

- Some feedback would be great. It was difficult so far, as we actually did hold some changes temporarily in the front-end until commit is pressed. We are considering to change it, which would also allow direct feedback.

- I hesitate because we could only guess and number them by their position in the list like "Scan 1, Scan 2, Scan 3", would that be more intuitive? Of course we could also guess XX, XX + 1, XX + 2 but it is not guaranteed that it is really correct. Please tell us your preference. @rtahseen is the splitting always strictly performed on full-pages? That'd make the guess a little more educated ;)

- Yes, its possible.

**Comment by anlausch** [comment]
1a) The preselection does not affect the back end, but the resource type is necessary. It is fine to put JOURNAL_ARTICLE + DOI. Monograph and Book can not be uploaded with the DOI at the moment, but we can add this later. The resource type is needed in order to know at which level of the hierarchy we are operating with the specific identifier and whether the combination of identifier and resource type and the other fields can be accepted.

**Comment by lgalke** [comment]
Okay, I see. Thanks for the explanation. We'll make JOURNAL_ARTICLE + DOI possible.

**Comment by rtahseen** [comment]
>     * @rtahseen is the splitting always strictly performed on full-pages?
When a PDF file is submitted for processing, it is splitted into pages and processing is performed for individual splitted page. Internally there is further spliting performed based on number of columns. But, finally the results are compiled and returned for each page.

**Comment by lgalke** [comment]
# Updates
- Chapters (or "children of the todo items") are now sorted depending on their `firstPage`. 
- The scan Number is now computed as `firstPage + index`. 

![screenshot_20181005_135917](https://user-images.githubusercontent.com/3439126/46534104-5a9afb00-c8a7-11e8-8233-64fd8ff5136a.png)

**Comment by lgalke** [comment]
Add some visual feedback 1bfca75

**Comment by lgalke** [comment]
![screenshot_20181006_115638](https://user-images.githubusercontent.com/3439126/46570066-fd628080-c95e-11e8-8518-a04bbb6d300a.png)

**Comment by lgalke** [comment]
All points are addressed except for

>resource type monograph & book should have the possibility to upload via DOI 

I'll open a specific issue for that, since it need back-end support in the first place
