### ISSUE TITLE
Zombie records in Agenda

### ISSUE THREAD

**Issue by kleinann** [locdb/locdb-frend#404]
In the dev version, there are e lot of entries without references in the electronic resources agenda. I noticed that I created a new one by just migrating an external suggestion to the database (it was "Personality Assessment via Questionnaires, Springer Berlin Heidelberg"). I don't now what you did to make these zombies go from the production database agenda - but please, don't let them come back ;-)

**Comment by lgalke** [comment]
Thanks for reporting this issue. Apparrently, we did not set the `status` to `valid` during the rework of the commit logic for the new buttons.


The status we have for suggestions `EXTERNAL` is the same that we have for ToDo items from electronic uploads.

@anlausch , would it make sense to set the status to 'VALID' in the back-end, when https://locdb.bib.uni-mannheim.de/locdb-dev/docs/#/BibliographicResource/save is called?
Guess it would be more robust and future-proof that way, especially because the statuses are so important for the back-end's behavior.

**Comment by anlausch** [comment]
Correct me in case I am wrong: I think we discussed that setting status from the backend is not possible for many cases. For example here, I cannot just assume that everything a user might want to save is a valid resource. Maybe he wants to manually ingest a new resource for adding references. However, I can forbid saving invalid resources. @lgalke would that make sense?

**Comment by lgalke** [comment]
> Maybe he wants to manually ingest a new resource for adding references. However, I can forbid saving invalid resources.

I see the point. The ingest service, however, uses the other service: https://locdb.bib.uni-mannheim.de/locdb-dev/docs/#/Scan/saveResource. 

So at the moment, the only cases, in which we call https://locdb.bib.uni-mannheim.de/locdb-dev/docs/#/BibliographicResource/save, is when a) external suggestions are migrated or b) a new container is manually created. In both cases the status should be always set to 'VALID'.

Anyways, I'm fine if we leave it like that. Maybe we want to make sure that the semantics of the statuses are, at some point, well-document.
