### ISSUE TITLE
Fix-It Button necessary

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#428]
I linked a few references in the production and noticed that if I migrate the article (=child) and then the issue (=parent), I need to click on fix-it or else the parent is not saved.
Additionally if I migrate the child and then click the yellow button to migrate the parent and link the resource the parent is not saved as well.
 I thought we fixed this with #354 but maybe I didn't test it enough and missed it. Could you please take another look?

**Comment by lgalke** [comment]
Does it work when the suggestion is taken as is, or not even in this case?

With all the modifications for creating new parents, new childs, and son it was difficult to always enable the short-cut link-to-this because in many cases we need some input from the user before we can successfully push the changes to the back-end. That's why right now the user has to press "Fix it".

Guess, it would make sense to immediately propagate the changes upwards and not just when 'migrate/submit' or 'fix it' is pressed. I'll need to verify that it is possible. Will let you know.

**Comment by lgalke** [comment]
7879aa1, deployed on dev. Could you test it please @LauraErhard

**Comment by LauraErhard** [comment]
If I change nothing and use the `Migrate 2 resources and link` directly it is saved correctly.
If I `migrate` the child because of changes and the parent is correct, so I don't have to save any changes and then click the `Migrate 1 resources and link` the parent is not saved.
If I `migrate` the child, then the parent **without** clicking `fix it` and then `link,` the parent is not saved.

**Comment by lgalke** [comment]
What happens on 'Link' or 'Migrate and Link':

1. If a container is given, migrate it *if external*
2. Migrate the child resource *if external*
3. Connect the child resource and the parent resource (via `partOf`)
4. If the reference entry already has another target, unlink it
5. Link the reference entry to the target (child) resource

What happens on 'Fix it'.
1. Sets the `partOf` property of the child to the `_id` of the parent or clear it, when stand-alone. Nothing else

What happens on `Submit | Migrate` within each resource form:

1. All changes to the resource are pushed to the back-end. (Please not that this happens only here)

**Comment by LauraErhard** [comment]
Oh sorry, I totally forgot, I was in the prod. In dev this works. 

But the case:

> If I migrate the child because of changes and the parent is correct, so I don't have to save any changes and then click the Migrate 1 resources and link the parent is not saved.

doesn't work. According to your explaination this would happen in part 3 (Connect the child resource and the parent resource (via partOf)), right? This part seems to still have a bug. In this case, we have to migrate child, migrate parent, press fix it and then link.

**Comment by lgalke** [comment]
Please test again. For me it worked:

![image](https://user-images.githubusercontent.com/3439126/49230047-10d61900-f3ef-11e8-8c98-e7419a3038cf.png)

I changed the title of the child (added `FANCY CHANGE`), migrated it, did not touch the container, and clicked the `Migrate 1 and submit` short-hand button.

**Comment by LauraErhard** [comment]
I just tested this.

I changed the subtitle & `migrated `child and then `Migrate 1 and link`. At first it looks good:
![2](https://user-images.githubusercontent.com/32642653/49230563-4596a000-f3f0-11e8-9220-8fa4418c4230.png)
But if I click to a different box and then back to it, I don't see the parent anymore:
![3](https://user-images.githubusercontent.com/32642653/49230564-47606380-f3f0-11e8-9ff9-5c38f41db2a4.png)

**Comment by lgalke** [comment]
This is strange, we *do* retrieve both the child and if it has `partOf` also the parent, when a new entry is selected.

**Comment by lgalke** [comment]
Fixed it now in f3ea95d . The problem was that if the thingy had an `_id` already, also the `partOf` changes were not pushed to the back-end (unless `Fix it` was pressed). Now, to have a more consistent behaviour of the 'Migrate x and Link' button, we do update the `partOf` property. Feel free to test again on dev, and let me know when I can push to prod.

**Comment by LauraErhard** [comment]
I think I just went through every possible scenario and everything worked nicely. 
As far as I'm concerned you can push the changes to production.
Thanks!
