### ISSUE TITLE
Set cites property on commit

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#45]
Set `cites` property of bibliographic resources when committing a link. So far, we only touch the `references` property of the entries

- [x] `cites` then has to be filled with the aggregate of `reference` values of the resource entries.
- [ ] The `TodoComponent` needs to keep track of the source resource.
- [x] Assert that back-end is aware of cites property
- [ ] The final commitment should happen in the `AppComponent` instead of the `SuggestionComponent`

**Comment by lgalke** [comment]
860de9cd3e910b0379fbf9bc2715e38e2c1cd413

**Comment by lgalke** [comment]
A method to sync `cites` with all `entry[x].references` properties is implemented, but for now we only called `/putBibliographicEntry` when the `commit` button is pressed. Instead we should call `/putBibliographicResource` to include the cites property as well as linked bibliographic entries. Do we want to update the entry at all?

**Comment by lgalke** [comment]
Depends on #51

**Comment by anlausch** [comment]
It is true that you do not have to use `PUT /BibliographicEntry` in case you use  `PUT /BibliographicResource` for the source resource and update there the `cites` property as well as the entries. Then you first would have to call  `POST /bibliographicResource` with the whatever merged resource (please take also care of the status) in order to create the target resource. It should return the resource which has now an `_id`. This `_id` should then be put in the `cites` property of the source resource and in the `references` property of the bibliographic entry in the source resource. Also, the `status` of the bibliographic entry needs to be updated. Then you can use `PUT /bibliographicResource` to update the source resource in the system.

Do you have anymore questions or ideas regarding that? Did I forget anything?

**Comment by lgalke** [comment]
The idea was also to commit usual changes like `link resource A to resource B` by `PUT /BibliographicResource` instead of `PUT BibliographicEntry`. That way the front-end could guarantee that the `cites` property is set correctly. However it would require quite some rearrangement since we currently only keep track of the `entry` and not the source resource itself. Do you have some kind of look-up table that relates the entries back to the resources, in which they appear? If yes, it might be easier to set the cites property on the back-end side, whenever `PUT /BibliographicEntry` is called.
What's your opinion on this?

**Comment by anlausch** [comment]
As discussed in a call between with lgalke, support will be provided by an additional backend service.

**Comment by lgalke** [comment]
Regarding the call: I assume that earlier or later, the front-end needs to keep track of the BResource to which the Entry was associated. So if it harms performance to *reverse-engineer* the corresponding resource, just provide `addTarget Source, Entry, Target`.

**Comment by anlausch** [comment]
Solution provided with https://github.com/locdb/loc-db/commit/cd4b82b80328541bf5937c1b9cbd345c8b49d1e6
