### ISSUE TITLE
saveScan malfunctioning

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#66]
Response when executing `/saveScan ...` in [Swagger](https://locdb.bib.uni-mannheim.de/locdb-dev/docs/)
```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid

response from an upstream server.<br />

The proxy server could not handle the request <em><a href="/locdb-dev/saveScan">POST&nbsp;/locdb-dev/saveScan</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p></p>
<hr>
<address>Apache/2.4.25 (Debian) Server at locdb.bib.uni-mannheim.de Port 443</address>
</body></html>
```

On local development setup, there is a cross-origin error:

```sh
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://locdb.bib.uni-mannheim.de/locdb-dev/saveScan. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

**Comment by anlausch** [comment]
Both locally and in the deployment setting the tests are still green. Further investigation showed that there were two problems related to this issue:
1) server crashes when invalid form-data parameters supplied; Fixed with https://github.com/locdb/loc-db/commit/6e7d59bf40c8b9cf746b4fc06382499a7a5b0329
2) server crashes on multipart/form-data when headers are set erroneously due to a middleware problem. Apparently some dependencies changes; Swagger-UI is also related to this issue

Problem 2) needs further investigation and maybe a temporary workaround but the front-end should now not encounter problems anymore if the requests are sent correctly.

**Comment by anlausch** [comment]
Back-end problem 2) solved with https://github.com/locdb/loc-db/commit/4286c4d7c7cc26d04ceca3e9b00772a4a24fa1f9

**Comment by lgalke** [comment]
Great, we should keep in mind that the PPN needs to exists in SWB.
