### ISSUE TITLE
Offset of extracted references

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#69]
There is a problem with the offset of extracted references, as shown in the picture:
Assumed coordinates format here was `x1 y1 x2 y2`

![locdb-screen](https://user-images.githubusercontent.com/3439126/31656459-e6edce94-b32b-11e7-81ad-6df793cd762f.png)

**Comment by lgalke** [comment]
After different interpretation `x1 x2 y1 y2` of the coordinates, it now looks as follows
![locdb-fail2](https://user-images.githubusercontent.com/3439126/31674174-6da64fee-b361-11e7-869f-3e04d2c0c9cc.png)

**Comment by rtahseen** [comment]
OCR component is returning coordinates in format **x1 y1 x2 y2**. If you closely look the first screenshot, you will realize that these coordinates are for references on right page only. This issue was already mentioned earlier and it is resolved in the new version. The offset is there due to cropping mechanism which is also resolved in the new version.

**Comment by lgalke** [comment]
That's great! I'll give it another try in the afternoon and good that the format is exactly the one we assumed so far.

**Comment by lgalke** [comment]
Will be fixed with the new ocr processing engine, same as #72 . One more test necessary before closing the issue.

**Comment by lgalke** [comment]
fixed by new ocr version
