### ISSUE TITLE
Fix specs

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#7]
In general the `travis.yml` is now working and specs are correctly executed.
However, the specs themselves are not meaningful yet and occasionally still miss some imports for the testing app module.

**Comment by zuphilip** [comment]
Great! We are now passing successfully now the Travis checks 🎉 .

**Comment by lgalke** [comment]
:+1: Still, greenkeeper does not start yet.

**Comment by zuphilip** [comment]
Okay, I deleted the (manually merged) Greenkeeper branch and tried to trigger Greenkeeper again for this repository, as it is suggested here https://github.com/greenkeeperio/greenkeeper/issues/402#issuecomment-297676799

Maybe, this already triggers Greenkeeper after some time ⌚️ ... I am not sure if deleting and readding is enough to trigger Greenkeeper. Otherwise we can also try to uninstall Greenkeeper completely and then readd it again afterwards.

**Comment by zuphilip** [comment]
After uninstall and install it looks good so far: Greenkeeper created a new branch. We have to wait now for CI and then Greenkeeper should continue...

**Comment by zuphilip** [comment]
Seems to work fine now, see #8. @lgalke Have a look at this PR and if it is good then you can merge it. Afterwards Greenkeeper should be active.

**Comment by lgalke** [comment]
:champagne: merged.
