### ISSUE TITLE
Date stored as an author in external suggestions

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#78]
Date is stored as an author in external suggestions.

**Comment by anlausch** [comment]
This issue is related to the google-scholar module. Probably it cannot parse the fields correctly anymore, as google scholar was recently updated. I created an issue for this:
https://github.com/VT-CHCI/google-scholar/issues/7

I will try to filter wrong results to bridge between now and an update from their side.

**Comment by anlausch** [comment]
Improved with https://github.com/locdb/loc-db/commit/cde3b8649d530ece413d3f9130f38f51cec53f61
