### ISSUE TITLE
Large queues of files cause OCR to take a long time

### ISSUE THREAD

**Issue by anlausch** [locdb/locdb-frend#90]
It seems to me that the ocr component is not very stable anymore. It just crashed again and similar behavior could be observed yesterday. Is it just not reachable because we sent too many requests?

14:55:14 26.10.2017 , Finished inputfile : 59edcac1889a22715c4de77d.pdf
14:46:28 26.10.2017 , Uploaded inputfile : 59edcac1889a22715c4de77d.pdf
14:46:01 26.10.2017 , Resetted the app

Also it seems that one file takes about 9 minutes?

**Comment by rtahseen** [comment]
I just checked the logs, OCR component was not crashed at all. It was overwhelmed with so many requests, even the logs shown a warning that it might be a DOS attack.

Also it is really not the case that OCR component takes 9 minutes to process the file. It took that time because someone has already queued a bunch of files ahead of you, for processing. It was unfortunate that your batch was in queue after that batch.

**Comment by anlausch** [comment]
Ok, if that's the issue - great! .. But I'll leave this issue open to keep it in mind and have an eye on it in the next days.

**Comment by rtahseen** [comment]
I checked the service again. The tag "OCR component unstable" is not suitable for the issue. The time when you submitted your file for processing, there were already 6 files in the queue containing ~ 18 pages. Therefore, your request was processed after completion of these 18 pages. This explains the time which you were waiting for. 
We are processing everything in a sequence and  parallel processing is not in the scope.
